### ISSUE TITLE
Deleting orders?

### ISSUE THREAD

**Issue by ardoster** [lolokraus/DegiroAPI#3]
I miss the possibility to delete orders. By checking this other API (https://github.com/Lanrutcon/DegiroAPI/blob/master/DegiroAPI/DegiroAPI.py), it looks like it should be quite easy.

It is in the roadmap this feature? Or maybe did you find problems? In case not, I'll try to include it by myself.

Thanks

**Comment by lolokraus** [comment]
Added the methode delete_order to delete an open order with the related orderId.
