### ISSUE TITLE
Retrieve the watchlists

### ISSUE THREAD

**Issue by viniciusmonteiro** [lolokraus/DegiroAPI#32]
It would be nice if we could also retrieve the favorite lists. Can we?

**Comment by Chavithra** [comment]
Hello there,

I have made a library which lets you retrieve favourites lists :

https://github.com/Chavithra/degiro-connector

It is the method : 

- get_favourites_list

Hope that  helps

**Comment by viniciusmonteiro** [comment]
Great, thanks!
