### ISSUE TITLE
Error 400 when placing online orders

### ISSUE THREAD

**Issue by MuppetJack** [lolokraus/DegiroAPI#37]
Hi,
It seems that since May 1st, the URL for placing buy or sell orders is sending back a 400 error code. Degiro may have changed/restricted their API access...

Thanks

**Comment by ArmykOliva** [comment]
Is it still a problem?

**Comment by MuppetJack** [comment]
Hi there,
Looks like it's working again. Issue closed on my side.

Thanks for the follow up!
