### ISSUE TITLE
delete order is not working properly

### ISSUE THREAD

**Issue by cyzelman** [lolokraus/DegiroAPI#39]
I would like to delete any open orders without indicating the order ID.
The code is shown in the picture.

Deleting with order ID is working just fine.

But I want to delete all open orders that are made within 24 hours, regardless the order ID.
I think the written code should serve this purpose. But it doesnt work.

Please help!

![Screenshot 2021-07-01 193652](https://user-images.githubusercontent.com/81416460/124166922-b79d5d00-daa3-11eb-8a24-5edca4e9e02c.jpg)

**Comment by Jakub-CZ** [comment]
It works for me. Check whether `delete_order` returns any errors. When the function is successful it should return an empty set `{}`.

**Comment by cyzelman** [comment]
i just checked i did not use pip install python-time and also did not import datetime and timedelta

case is close

**Comment by cyzelman** [comment]
I see what the happened.

 

You guys did not tell me to install python-time and also to import datetime and timedelta. Below is the only instruction.

I think you should update the dependencies and imports. I’m sure I’m not the only one (no python experience whatsoever) who face this issue.

 

Thanks.

 



 

Gr, Chris
