### ISSUE TITLE
How to get product ID from ISIN?

### ISSUE THREAD

**Issue by cyzelman** [lolokraus/DegiroAPI#40]
I'm trading most of the time only turbos, so it doesnt have a name only ISIN.

How to get product ID from an ISIN?

for example what is the product ID of DE000KE04K89 ?

Now I just create fake order and get the order list with python then I can see the product ID. But there should be a smarter way.

Please help, it means a lot to me.

**Comment by Jakub-CZ** [comment]
Dude, you're getting stuck on trivial non-problems.

**A)** DE000KE04K89 is not available on Degiro, which you could've figured out yourself by a simple search in 5 seconds.

**B)** For any product that **is** available on Degiro, you can use `search_products`, providing the ISIN, and you'll get the product ID (among other things).


```python
from degiroapi.product import Product

products = [Product(p) for p in degiro.search_products("DE000VL97TB2")]
for p in products:
    print(f"{p.id=}, {p.isin=}, {p.name=}")
```

Output:
```
p.id='14540292', p.isin='DE000VL97TB2', p.name='AHOLD SL 17.13  HB 3.12  FN 17.13  R 1.00 Vontobel BEST Turbo Long'
```

**Comment by cyzelman** [comment]
Thanks!

 

I will use your code to get the product ID.

 

Fast response btw!

 

Gr, Chris

**Comment by cyzelman** [comment]
closed
