### ISSUE TITLE
something changed 22-11-2021 afternoon. does not work anymore

### ISSUE THREAD

**Issue by Epenko** [lolokraus/DegiroAPI#47]
Does not work anymore, from this afternoon. This morning it worked just fine.
(Could have something to do with the zero-costs policy that was also introduced today / so probably some other stuff changed also?)
i hope it is something small

**Comment by Jakub-CZ** [comment]
Degiro's having trouble loading even via their web interface - clearly not an issue with this package.

**Comment by Epenko** [comment]
yes, it works again! Here i didn't encounter problems with the site, so i wasn't aware of any problems, but encountered problems with the package.  Thanks
