### ISSUE TITLE
DegiroApi - Could not login.

### ISSUE THREAD

**Issue by JMKwins** [lolokraus/DegiroAPI#57]
Hello Houston, 
It seems that we have a problem connecting. 
Since today connections fail to DEGIRO using DegiroAPI. 
I receive an exception message:

login_response = self.__request(DeGiro.__LOGIN_URL, None, login_payload, request_type=DeGiro.__POST_REQUEST,
     45                                     error_message='Could not login.')
     46     self.session_id = login_response['sessionId']
     47     client_info_payload = {'sessionId': self.session_id}

 <h1>You are not supposed to be here</h1>  

I would except to be not alone with this error message. 
Br,

**Comment by Jakub-CZ** [comment]
See #56

**Comment by JMKwins** [comment]
ok thanks for the support.
we can close

**Comment by JMKwins** [comment]
See #56
