### ISSUE TITLE
Unable to login with degiroapi

### ISSUE THREAD

**Issue by rockmesh** [lolokraus/DegiroAPI#58]
Starting from a couple of days, i am not able to login with degiroapi.
I get an html response with the header "_You are not supposed to be here_"

I've checked my uname and pwd and they are ok.
Does Degiro have blocked the access through APIs?

**Comment by Jakub-CZ** [comment]
#56

**Comment by rockmesh** [comment]
Your suggestion solves the issue.
You should merge it on the master, official release is still 0.9.5.
Thanks
